import { ImageResponse } from "@vercel/og";

export const runtime = "edge";

interface SnapshotRequest {
  studioName: string;
  date: string;
  instructors: Array<{
    name: string;
    specialization: string;
    statusText: string;
  }>;
}

export async function POST(request: Request) {
  try {
    const body: SnapshotRequest = await request.json();
    const { studioName, date, instructors } = body;

    return new ImageResponse(
      (
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            flexDirection: "column",
            backgroundColor: "#ffffff",
            padding: "60px",
          }}
        >
          {/* Header */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              marginBottom: "40px",
            }}
          >
            <div
              style={{
                fontSize: "48px",
                fontWeight: "bold",
                color: "#0369a1",
                marginBottom: "12px",
              }}
            >
              {studioName}
            </div>
            <div
              style={{
                fontSize: "32px",
                color: "#475569",
              }}
            >
              {date}
            </div>
          </div>

          {/* Divider */}
          <div
            style={{
              width: "100%",
              height: "3px",
              backgroundColor: "#0ea5e9",
              marginBottom: "40px",
            }}
          />

          {/* Instructor Table */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "16px",
            }}
          >
            {/* Table Header */}
            <div
              style={{
                display: "flex",
                backgroundColor: "#f1f5f9",
                padding: "20px 24px",
                borderRadius: "8px",
              }}
            >
              <div
                style={{
                  flex: "2",
                  fontSize: "24px",
                  fontWeight: "600",
                  color: "#0f172a",
                }}
              >
                Instructor
              </div>
              <div
                style={{
                  flex: "1",
                  fontSize: "24px",
                  fontWeight: "600",
                  color: "#0f172a",
                }}
              >
                Specialization
              </div>
              <div
                style={{
                  flex: "2",
                  fontSize: "24px",
                  fontWeight: "600",
                  color: "#0f172a",
                }}
              >
                Availability
              </div>
            </div>

            {/* Table Rows */}
            {instructors.slice(0, 12).map((instructor, index) => (
              <div
                key={index}
                style={{
                  display: "flex",
                  padding: "20px 24px",
                  backgroundColor: index % 2 === 0 ? "#ffffff" : "#f8fafc",
                  borderRadius: "8px",
                  border: "1px solid #e2e8f0",
                }}
              >
                <div
                  style={{
                    flex: "2",
                    fontSize: "22px",
                    color: "#1e293b",
                    fontWeight: "500",
                  }}
                >
                  {instructor.name}
                </div>
                <div
                  style={{
                    flex: "1",
                    fontSize: "20px",
                    color: "#475569",
                  }}
                >
                  {instructor.specialization}
                </div>
                <div
                  style={{
                    flex: "2",
                    fontSize: "20px",
                    color: getStatusColor(instructor.statusText),
                    fontWeight: "500",
                  }}
                >
                  {instructor.statusText}
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div
            style={{
              marginTop: "auto",
              paddingTop: "40px",
              fontSize: "18px",
              color: "#94a3b8",
              textAlign: "center",
            }}
          >
            Generated by Haya Studio Demo
          </div>
        </div>
      ),
      {
        width: 1080,
        height: 1350,
      }
    );
  } catch (error) {
    console.error("Error generating snapshot:", error);
    return new Response("Error generating snapshot", { status: 500 });
  }
}

function getStatusColor(statusText: string): string {
  if (statusText.includes("On Leave")) {
    return "#ca8a04";
  }
  if (statusText === "Not Available") {
    return "#64748b";
  }
  return "#059669";
}
