import { ImageResponse } from "@vercel/og";

export const runtime = "edge";

interface SnapshotRequest {
  studioName: string;
  date: string;
  instructors: Array<{
    name: string;
    specialization: string;
    statusText: string;
  }>;
}

export async function POST(request: Request) {
  try {
    const body: SnapshotRequest = await request.json();
    const { studioName, date, instructors } = body;

    return new ImageResponse(
      (
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            flexDirection: "column",
            background: "linear-gradient(135deg, #09090b 0%, #18181b 100%)",
            padding: "60px",
          }}
        >
          {/* Header */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              marginBottom: "40px",
            }}
          >
            <div
              style={{
                fontSize: "52px",
                fontWeight: "bold",
                color: "#ffffff",
                marginBottom: "8px",
                letterSpacing: "-0.02em",
              }}
            >
              {studioName}
            </div>
            <div
              style={{
                fontSize: "28px",
                color: "#14b8a6",
                fontWeight: "600",
              }}
            >
              {date}
            </div>
          </div>

          {/* Divider */}
          <div
            style={{
              width: "100%",
              height: "4px",
              background: "linear-gradient(90deg, #14b8a6 0%, #0d9488 100%)",
              marginBottom: "40px",
              borderRadius: "2px",
            }}
          />

          {/* Instructor Table */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "12px",
            }}
          >
            {/* Table Header */}
            <div
              style={{
                display: "flex",
                backgroundColor: "#27272a",
                padding: "18px 24px",
                borderRadius: "12px",
                border: "1px solid #3f3f46",
              }}
            >
              <div
                style={{
                  flex: "2",
                  fontSize: "22px",
                  fontWeight: "600",
                  color: "#a1a1aa",
                }}
              >
                Instructor
              </div>
              <div
                style={{
                  flex: "1",
                  fontSize: "22px",
                  fontWeight: "600",
                  color: "#a1a1aa",
                }}
              >
                Specialization
              </div>
              <div
                style={{
                  flex: "2",
                  fontSize: "22px",
                  fontWeight: "600",
                  color: "#a1a1aa",
                }}
              >
                Status
              </div>
            </div>

            {/* Table Rows */}
            {instructors.slice(0, 12).map((instructor, index) => (
              <div
                key={index}
                style={{
                  display: "flex",
                  padding: "18px 24px",
                  backgroundColor: index % 2 === 0 ? "#18181b" : "#09090b",
                  borderRadius: "12px",
                  border: "1px solid #27272a",
                }}
              >
                <div
                  style={{
                    flex: "2",
                    fontSize: "20px",
                    color: "#fafafa",
                    fontWeight: "500",
                  }}
                >
                  {instructor.name}
                </div>
                <div
                  style={{
                    flex: "1",
                    fontSize: "18px",
                    color: "#a1a1aa",
                  }}
                >
                  {instructor.specialization}
                </div>
                <div
                  style={{
                    flex: "2",
                    fontSize: "18px",
                    color: getStatusColor(instructor.statusText),
                    fontWeight: "600",
                  }}
                >
                  {instructor.statusText}
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div
            style={{
              marginTop: "auto",
              paddingTop: "40px",
              fontSize: "16px",
              color: "#52525b",
              textAlign: "center",
              fontWeight: "500",
            }}
          >
            Generated by Haya Studio Demo
          </div>
        </div>
      ),
      {
        width: 1080,
        height: 1350,
      }
    );
  } catch (error) {
    console.error("Error generating snapshot:", error);
    return new Response("Error generating snapshot", { status: 500 });
  }
}

function getStatusColor(statusText: string): string {
  if (statusText.includes("On Leave")) {
    return "#facc15";
  }
  if (statusText === "Not Available") {
    return "#71717a";
  }
  return "#14b8a6";
}
